services:
  db:
    image: mysql:8.0
    container_name: fuel-db
    restart: always
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      # make sure your DB_PASSWORD is correct mine is root
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fuel_calculator_localization
      MYSQL_USER: fuel_app_user     # dedicated DB user for your app
      MYSQL_PASSWORD: password   # password for the app user
      # Make sure your 3307 port is available
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "mysql -h 127.0.0.1 -P 3306 -u root -proot -e 'SELECT 1'"]
      interval: 5s
      timeout: 5s
      retries: 20
      start_period: 30s

  app:
    # image is my own account for the exercise you have to change to your account
    #IMPORTANT docker build -t yourname/sum-product-fx .
    # docker push yourname/sum-product-fx: last
    # then you can change the image in the following statment
    image: aleksi246/otp2w2_demo_w3:latest
    container_name: otp2w2_demo_w3
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_URL: jdbc:mysql://fuel-db:3306/fuel_calculator_localization?useUnicode=true&characterEncoding=UTF-8
      # make sure your DB_USER name is correct mine is root
      DB_USER: fuel_app_user
      # make sure your DB_PASSWORD is correct mine is root
      DB_PASSWORD: password
      DISPLAY: host.docker.internal:0
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
#    network_mode: bridge # it cancels network of docker -> docker cannot find host db.
volumes:
  db_data:

#  Then execute docker compose up --build